# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quoridor_rl_v8.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'quoridor_rl_v8.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14quoridor_rl_v8.proto\x12\x0equoridor_rl_v8\"\x0e\n\x0cResetRequest\"\x1d\n\x0bStepRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"\xc9\x01\n\x08\x45nvState\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x13\n\x0b\x61\x63tion_mask\x18\x02 \x03(\x08\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x12\x16\n\x0e\x63urrent_player\x18\x05 \x01(\x05\x12\x30\n\x04info\x18\x06 \x03(\x0b\x32\".quoridor_rl_v8.EnvState.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x8d\x01\n\x0bQuoridorEnv\x12?\n\x05Reset\x12\x1c.quoridor_rl_v8.ResetRequest\x1a\x18.quoridor_rl_v8.EnvState\x12=\n\x04Step\x12\x1b.quoridor_rl_v8.StepRequest\x1a\x18.quoridor_rl_v8.EnvStateB\x1eZ\x1cquoridor/internal/rlv8/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quoridor_rl_v8_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034quoridor/internal/rlv8/pb;pb'
  _globals['_ENVSTATE_INFOENTRY']._loaded_options = None
  _globals['_ENVSTATE_INFOENTRY']._serialized_options = b'8\001'
  _globals['_RESETREQUEST']._serialized_start=40
  _globals['_RESETREQUEST']._serialized_end=54
  _globals['_STEPREQUEST']._serialized_start=56
  _globals['_STEPREQUEST']._serialized_end=85
  _globals['_ENVSTATE']._serialized_start=88
  _globals['_ENVSTATE']._serialized_end=289
  _globals['_ENVSTATE_INFOENTRY']._serialized_start=246
  _globals['_ENVSTATE_INFOENTRY']._serialized_end=289
  _globals['_QUORIDORENV']._serialized_start=292
  _globals['_QUORIDORENV']._serialized_end=433
# @@protoc_insertion_point(module_scope)
