// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: quoridor_rl_v8.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuoridorEnv_Reset_FullMethodName = "/quoridor_rl_v8.QuoridorEnv/Reset"
	QuoridorEnv_Step_FullMethodName  = "/quoridor_rl_v8.QuoridorEnv/Step"
)

// QuoridorEnvClient is the client API for QuoridorEnv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoridorEnvClient interface {
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*EnvState, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*EnvState, error)
}

type quoridorEnvClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoridorEnvClient(cc grpc.ClientConnInterface) QuoridorEnvClient {
	return &quoridorEnvClient{cc}
}

func (c *quoridorEnvClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*EnvState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvState)
	err := c.cc.Invoke(ctx, QuoridorEnv_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoridorEnvClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*EnvState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvState)
	err := c.cc.Invoke(ctx, QuoridorEnv_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoridorEnvServer is the server API for QuoridorEnv service.
// All implementations must embed UnimplementedQuoridorEnvServer
// for forward compatibility.
type QuoridorEnvServer interface {
	Reset(context.Context, *ResetRequest) (*EnvState, error)
	Step(context.Context, *StepRequest) (*EnvState, error)
	mustEmbedUnimplementedQuoridorEnvServer()
}

// UnimplementedQuoridorEnvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuoridorEnvServer struct{}

func (UnimplementedQuoridorEnvServer) Reset(context.Context, *ResetRequest) (*EnvState, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedQuoridorEnvServer) Step(context.Context, *StepRequest) (*EnvState, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedQuoridorEnvServer) mustEmbedUnimplementedQuoridorEnvServer() {}
func (UnimplementedQuoridorEnvServer) testEmbeddedByValue()                     {}

// UnsafeQuoridorEnvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoridorEnvServer will
// result in compilation errors.
type UnsafeQuoridorEnvServer interface {
	mustEmbedUnimplementedQuoridorEnvServer()
}

func RegisterQuoridorEnvServer(s grpc.ServiceRegistrar, srv QuoridorEnvServer) {
	// If the following call panics, it indicates UnimplementedQuoridorEnvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuoridorEnv_ServiceDesc, srv)
}

func _QuoridorEnv_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoridorEnvServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoridorEnv_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoridorEnvServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoridorEnv_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoridorEnvServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoridorEnv_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoridorEnvServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoridorEnv_ServiceDesc is the grpc.ServiceDesc for QuoridorEnv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoridorEnv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quoridor_rl_v8.QuoridorEnv",
	HandlerType: (*QuoridorEnvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _QuoridorEnv_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _QuoridorEnv_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quoridor_rl_v8.proto",
}
