// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: quoridor_rl_v8.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_quoridor_rl_v8_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quoridor_rl_v8_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_quoridor_rl_v8_proto_rawDescGZIP(), []int{0}
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_quoridor_rl_v8_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quoridor_rl_v8_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_quoridor_rl_v8_proto_rawDescGZIP(), []int{1}
}

func (x *StepRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type EnvState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   []float32              `protobuf:"fixed32,1,rep,packed,name=observation,proto3" json:"observation,omitempty"`
	ActionMask    []bool                 `protobuf:"varint,2,rep,packed,name=action_mask,json=actionMask,proto3" json:"action_mask,omitempty"`
	Reward        float32                `protobuf:"fixed32,3,opt,name=reward,proto3" json:"reward,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	CurrentPlayer int32                  `protobuf:"varint,5,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"`
	Info          map[string]float32     `protobuf:"bytes,6,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvState) Reset() {
	*x = EnvState{}
	mi := &file_quoridor_rl_v8_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvState) ProtoMessage() {}

func (x *EnvState) ProtoReflect() protoreflect.Message {
	mi := &file_quoridor_rl_v8_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvState.ProtoReflect.Descriptor instead.
func (*EnvState) Descriptor() ([]byte, []int) {
	return file_quoridor_rl_v8_proto_rawDescGZIP(), []int{2}
}

func (x *EnvState) GetObservation() []float32 {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *EnvState) GetActionMask() []bool {
	if x != nil {
		return x.ActionMask
	}
	return nil
}

func (x *EnvState) GetReward() float32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *EnvState) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *EnvState) GetCurrentPlayer() int32 {
	if x != nil {
		return x.CurrentPlayer
	}
	return 0
}

func (x *EnvState) GetInfo() map[string]float32 {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_quoridor_rl_v8_proto protoreflect.FileDescriptor

const file_quoridor_rl_v8_proto_rawDesc = "" +
	"\n" +
	"\x14quoridor_rl_v8.proto\x12\x0equoridor_rl_v8\"\x0e\n" +
	"\fResetRequest\"%\n" +
	"\vStepRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\"\x91\x02\n" +
	"\bEnvState\x12 \n" +
	"\vobservation\x18\x01 \x03(\x02R\vobservation\x12\x1f\n" +
	"\vaction_mask\x18\x02 \x03(\bR\n" +
	"actionMask\x12\x16\n" +
	"\x06reward\x18\x03 \x01(\x02R\x06reward\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12%\n" +
	"\x0ecurrent_player\x18\x05 \x01(\x05R\rcurrentPlayer\x126\n" +
	"\x04info\x18\x06 \x03(\v2\".quoridor_rl_v8.EnvState.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012\x8d\x01\n" +
	"\vQuoridorEnv\x12?\n" +
	"\x05Reset\x12\x1c.quoridor_rl_v8.ResetRequest\x1a\x18.quoridor_rl_v8.EnvState\x12=\n" +
	"\x04Step\x12\x1b.quoridor_rl_v8.StepRequest\x1a\x18.quoridor_rl_v8.EnvStateB\x1eZ\x1cquoridor/internal/rlv8/pb;pbb\x06proto3"

var (
	file_quoridor_rl_v8_proto_rawDescOnce sync.Once
	file_quoridor_rl_v8_proto_rawDescData []byte
)

func file_quoridor_rl_v8_proto_rawDescGZIP() []byte {
	file_quoridor_rl_v8_proto_rawDescOnce.Do(func() {
		file_quoridor_rl_v8_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quoridor_rl_v8_proto_rawDesc), len(file_quoridor_rl_v8_proto_rawDesc)))
	})
	return file_quoridor_rl_v8_proto_rawDescData
}

var file_quoridor_rl_v8_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_quoridor_rl_v8_proto_goTypes = []any{
	(*ResetRequest)(nil), // 0: quoridor_rl_v8.ResetRequest
	(*StepRequest)(nil),  // 1: quoridor_rl_v8.StepRequest
	(*EnvState)(nil),     // 2: quoridor_rl_v8.EnvState
	nil,                  // 3: quoridor_rl_v8.EnvState.InfoEntry
}
var file_quoridor_rl_v8_proto_depIdxs = []int32{
	3, // 0: quoridor_rl_v8.EnvState.info:type_name -> quoridor_rl_v8.EnvState.InfoEntry
	0, // 1: quoridor_rl_v8.QuoridorEnv.Reset:input_type -> quoridor_rl_v8.ResetRequest
	1, // 2: quoridor_rl_v8.QuoridorEnv.Step:input_type -> quoridor_rl_v8.StepRequest
	2, // 3: quoridor_rl_v8.QuoridorEnv.Reset:output_type -> quoridor_rl_v8.EnvState
	2, // 4: quoridor_rl_v8.QuoridorEnv.Step:output_type -> quoridor_rl_v8.EnvState
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quoridor_rl_v8_proto_init() }
func file_quoridor_rl_v8_proto_init() {
	if File_quoridor_rl_v8_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quoridor_rl_v8_proto_rawDesc), len(file_quoridor_rl_v8_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quoridor_rl_v8_proto_goTypes,
		DependencyIndexes: file_quoridor_rl_v8_proto_depIdxs,
		MessageInfos:      file_quoridor_rl_v8_proto_msgTypes,
	}.Build()
	File_quoridor_rl_v8_proto = out.File
	file_quoridor_rl_v8_proto_goTypes = nil
	file_quoridor_rl_v8_proto_depIdxs = nil
}
