// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/quoridor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpponentType  int32                  `protobuf:"varint,1,opt,name=opponent_type,json=opponentType,proto3" json:"opponent_type,omitempty"` // 0: Heurístico, 1: Minimax3, 2: Minimax4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_quoridor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quoridor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_quoridor_proto_rawDescGZIP(), []int{0}
}

func (x *ResetRequest) GetOpponentType() int32 {
	if x != nil {
		return x.OpponentType
	}
	return 0
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      int32                  `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"` // ID de acción única (0 - 139)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_proto_quoridor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quoridor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_proto_quoridor_proto_rawDescGZIP(), []int{1}
}

func (x *StepRequest) GetActionId() int32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateTensor   []float32              `protobuf:"fixed32,1,rep,packed,name=state_tensor,json=stateTensor,proto3" json:"state_tensor,omitempty"` // Estado del tablero (294 floats)
	ActionMask    []bool                 `protobuf:"varint,2,rep,packed,name=action_mask,json=actionMask,proto3" json:"action_mask,omitempty"`     // Máscara de acciones válidas (140 bools)
	Reward        float32                `protobuf:"fixed32,3,opt,name=reward,proto3" json:"reward,omitempty"`                                     // Recompensa del turno
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`                                          // Fin de la partida
	Winner        int32                  `protobuf:"varint,5,opt,name=winner,proto3" json:"winner,omitempty"`                                      // ID del ganador (0 si continúa)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_proto_quoridor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quoridor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_proto_quoridor_proto_rawDescGZIP(), []int{2}
}

func (x *StepResponse) GetStateTensor() []float32 {
	if x != nil {
		return x.StateTensor
	}
	return nil
}

func (x *StepResponse) GetActionMask() []bool {
	if x != nil {
		return x.ActionMask
	}
	return nil
}

func (x *StepResponse) GetReward() float32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResponse) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

var File_proto_quoridor_proto protoreflect.FileDescriptor

const file_proto_quoridor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/quoridor.proto\x12\bquoridor\"3\n" +
	"\fResetRequest\x12#\n" +
	"\ropponent_type\x18\x01 \x01(\x05R\fopponentType\"*\n" +
	"\vStepRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x05R\bactionId\"\x96\x01\n" +
	"\fStepResponse\x12!\n" +
	"\fstate_tensor\x18\x01 \x03(\x02R\vstateTensor\x12\x1f\n" +
	"\vaction_mask\x18\x02 \x03(\bR\n" +
	"actionMask\x12\x16\n" +
	"\x06reward\x18\x03 \x01(\x02R\x06reward\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x16\n" +
	"\x06winner\x18\x05 \x01(\x05R\x06winner2}\n" +
	"\vQuoridorEnv\x127\n" +
	"\x05Reset\x12\x16.quoridor.ResetRequest\x1a\x16.quoridor.StepResponse\x125\n" +
	"\x04Step\x12\x15.quoridor.StepRequest\x1a\x16.quoridor.StepResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_proto_quoridor_proto_rawDescOnce sync.Once
	file_proto_quoridor_proto_rawDescData []byte
)

func file_proto_quoridor_proto_rawDescGZIP() []byte {
	file_proto_quoridor_proto_rawDescOnce.Do(func() {
		file_proto_quoridor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quoridor_proto_rawDesc), len(file_proto_quoridor_proto_rawDesc)))
	})
	return file_proto_quoridor_proto_rawDescData
}

var file_proto_quoridor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_quoridor_proto_goTypes = []any{
	(*ResetRequest)(nil), // 0: quoridor.ResetRequest
	(*StepRequest)(nil),  // 1: quoridor.StepRequest
	(*StepResponse)(nil), // 2: quoridor.StepResponse
}
var file_proto_quoridor_proto_depIdxs = []int32{
	0, // 0: quoridor.QuoridorEnv.Reset:input_type -> quoridor.ResetRequest
	1, // 1: quoridor.QuoridorEnv.Step:input_type -> quoridor.StepRequest
	2, // 2: quoridor.QuoridorEnv.Reset:output_type -> quoridor.StepResponse
	2, // 3: quoridor.QuoridorEnv.Step:output_type -> quoridor.StepResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_quoridor_proto_init() }
func file_proto_quoridor_proto_init() {
	if File_proto_quoridor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quoridor_proto_rawDesc), len(file_proto_quoridor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quoridor_proto_goTypes,
		DependencyIndexes: file_proto_quoridor_proto_depIdxs,
		MessageInfos:      file_proto_quoridor_proto_msgTypes,
	}.Build()
	File_proto_quoridor_proto = out.File
	file_proto_quoridor_proto_goTypes = nil
	file_proto_quoridor_proto_depIdxs = nil
}
