# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quoridor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'quoridor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equoridor.proto\x12\x08quoridor\"%\n\x0cResetRequest\x12\x15\n\ropponent_type\x18\x01 \x01(\x05\" \n\x0bStepRequest\x12\x11\n\taction_id\x18\x01 \x01(\x05\"g\n\x0cStepResponse\x12\x14\n\x0cstate_tensor\x18\x01 \x03(\x02\x12\x13\n\x0b\x61\x63tion_mask\x18\x02 \x03(\x08\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x12\x0e\n\x06winner\x18\x05 \x01(\x05\x32}\n\x0bQuoridorEnv\x12\x37\n\x05Reset\x12\x16.quoridor.ResetRequest\x1a\x16.quoridor.StepResponse\x12\x35\n\x04Step\x12\x15.quoridor.StepRequest\x1a\x16.quoridor.StepResponseB\rZ\x0binternal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quoridor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013internal/pb'
  _globals['_RESETREQUEST']._serialized_start=28
  _globals['_RESETREQUEST']._serialized_end=65
  _globals['_STEPREQUEST']._serialized_start=67
  _globals['_STEPREQUEST']._serialized_end=99
  _globals['_STEPRESPONSE']._serialized_start=101
  _globals['_STEPRESPONSE']._serialized_end=204
  _globals['_QUORIDORENV']._serialized_start=206
  _globals['_QUORIDORENV']._serialized_end=331
# @@protoc_insertion_point(module_scope)
